### ISSUE TITLE
code completions should work soon

### ISSUE THREAD

**Issue by archaistvolts** [nothke/zigdown#4]
I noticed on stream that completions were missing here and in similar cases when you were slicing/indexing a multi pointer.

https://github.com/nothke/zigdown/blob/07053a4ad19704b4ecb39c65ba1b23a1a6da7b69/src/main.zig#L136

That should be fixed once this issue i created and made a PR for is closed: https://github.com/zigtools/zls/pull/1484

Sorry for abusing your issue tracker like this.  Just thought you'd be happy to have better completions soon.

**Comment by nothke** [comment]
No problem at all. Thank you very much! And thanks for improving zls! Glad I helped spot the issue :)

**Comment by archaistvolts** [comment]
Yeah you really did help spot the issue.  If you run into any other zls problems, don't hesitate to open an issue.  This was a really easy fix thanks to some help from Techatrix in the zls discord and in the issue.

**Comment by archaistvolts** [comment]
merged.

**Comment by nothke** [comment]
Perfect! Thanks!
